# Generated by Django 6.0.2 on 2026-02-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_code',
            new_name='country',
        ),
    ]
