# Generated by Django 6.0.2 on 2026-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_rename_country_code_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
