# Generated by Django 6.0.2 on 2026-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_country_alter_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infotype',
            name='id',
        ),
        migrations.AlterField(
            model_name='infotype',
            name='type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
