# Generated by Django 6.0.2 on 2026-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_remove_infotype_id_alter_infotype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotype',
            name='icon',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
