# Generated by Django 6.0.2 on 2026-02-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_alter_infotype_icon_alter_weather_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='name',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
    ]
