# Generated by Django 6.0.2 on 2026-03-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_alter_city_lat_alter_city_lon_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='', max_length=80),
        ),
    ]
