# Generated by Django 6.0.2 on 2026-07-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_city_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
